
package game.answer.place.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapServicesImplService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/soap/SoapServicesImpl?wsdl")
public class SoapServicesImplService
    extends Service
{

    private final static URL SOAPSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName SOAPSERVICESIMPLSERVICE_QNAME = new QName("http://soap/", "SoapServicesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/SoapServicesImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICESIMPLSERVICE_WSDL_LOCATION = url;
        SOAPSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public SoapServicesImplService() {
        super(__getWsdlLocation(), SOAPSERVICESIMPLSERVICE_QNAME);
    }

    public SoapServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICESIMPLSERVICE_QNAME, features);
    }

    public SoapServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICESIMPLSERVICE_QNAME);
    }

    public SoapServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICESIMPLSERVICE_QNAME, features);
    }

    public SoapServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapServices
     */
    @WebEndpoint(name = "SoapServicesImplPort")
    public SoapServices getSoapServicesImplPort() {
        return super.getPort(new QName("http://soap/", "SoapServicesImplPort"), SoapServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapServices
     */
    @WebEndpoint(name = "SoapServicesImplPort")
    public SoapServices getSoapServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "SoapServicesImplPort"), SoapServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICESIMPLSERVICE_EXCEPTION;
        }
        return SOAPSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
