
package com.gamewsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameSoapServiceService", targetNamespace = "http://place.answer.game/", wsdlLocation = "http://localhost:8080/game/GameSoapService?wsdl")
public class GameSoapServiceService
    extends Service
{

    private final static URL GAMESOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMESOAPSERVICESERVICE_EXCEPTION;
    private final static QName GAMESOAPSERVICESERVICE_QNAME = new QName("http://place.answer.game/", "GameSoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/game/GameSoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMESOAPSERVICESERVICE_WSDL_LOCATION = url;
        GAMESOAPSERVICESERVICE_EXCEPTION = e;
    }

    public GameSoapServiceService() {
        super(__getWsdlLocation(), GAMESOAPSERVICESERVICE_QNAME);
    }

    public GameSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMESOAPSERVICESERVICE_QNAME, features);
    }

    public GameSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, GAMESOAPSERVICESERVICE_QNAME);
    }

    public GameSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMESOAPSERVICESERVICE_QNAME, features);
    }

    public GameSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameSoapServiceImpl
     */
    @WebEndpoint(name = "GameSoapServicePort")
    public GameSoapServiceImpl getGameSoapServicePort() {
        return super.getPort(new QName("http://place.answer.game/", "GameSoapServicePort"), GameSoapServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameSoapServiceImpl
     */
    @WebEndpoint(name = "GameSoapServicePort")
    public GameSoapServiceImpl getGameSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://place.answer.game/", "GameSoapServicePort"), GameSoapServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMESOAPSERVICESERVICE_EXCEPTION!= null) {
            throw GAMESOAPSERVICESERVICE_EXCEPTION;
        }
        return GAMESOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
